# Group PasswordRecovers
Welcome to the password recovers API. This API provides access to the password recovers service.

## password recovers [/password_recovers]

### Create password recover [POST]

Create a new password recover

+ Request password recover (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json
    + Attributes

        + user_id: 1 (number)
        + hash: HASH (string)

+ Response 201 (application/json; charset=utf-8)
    + Attributes (password_recover, fixed)

### Get password recovers [GET]

Returns a password recover list.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (array, fixed)
        + (password_recover)

## password recover details [/password_recovers/{id}]

+ Parameters
    + id: `1` (enum[string]) - The ID of the desired password recover.
        + Members
            + `1`
            + `2`
            + `3`

### Get password recover [GET]

Returns a password recover.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 200 (application/json; charset=utf-8)
    + Attributes (password_recover, fixed)

### Update password recover [PUT]

Update a password recover.

+ Request password_recover (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json
    + Attributes

        + user_id: 1 (number)
        + hash: HASH (string)

+ Response 200 (application/json; charset=utf-8)
    + Attributes (password_recover, fixed)

### Delete password recover [DELETE]

Delete a password recover.

+ Request (application/json; charset=utf-8)
    + Headers

            Accept: application/vnd.filiponegrao+json

+ Response 204

# Data Structures
## password_recover (object)

+ id: *1* (number)
+ user_id: *1* (number)
+ hash: *HASH* (string)
+ createdAt: `*2000-01-01 00:00:00*` (string)
+ updatedAt: `*2000-01-01 00:00:00*` (string)
